upstream backend {
      server 192.168.88.207:80;
      server 192.168.88.206:80;           
    }
    server {
      listen 80;
      server_name nginx-1.local;
      location / {
        proxy_pass http://backend;
      }
    }
